### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by kepler**

### CODE REVIEW

**Comment by q0o0p** [comment]
Looks like commit '348cdbf' duplicates PR #122

**Comment by kepler** [comment]
> Looks like commit '348cdbf' duplicates PR #122

Good catch. @ramon-astudillo, could you please merge the #122? And then this one, if you agree, since it changes more stuff in the RL chapter.

**Comment by ramon-astudillo** [comment]
Manually merged @kepler, @q0o0p please have a look just int case.

**Comment by q0o0p** [comment]
@ramon-astudillo,  some changes were accidentally lost during this merge.
Please see PR #127

**Pull request merged**
